services:
  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: lend
      MONGO_INITDB_ROOT_PASSWORD: lend_secret
      MONGO_INITDB_DATABASE: lending_db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "-u",
          "lend",
          "-p",
          "lend_secret",
          "--authenticationDatabase",
          "admin",
          "--quiet",
          "--eval",
          "db.adminCommand({ ping: 1 }).ok",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongodata:
